### ISSUE TITLE
Nightly Build

### ISSUE THREAD

**Issue by ManticSic** [CSharpAnalyzers/ExceptionalReSharper#99]
Provide a nightly build (not stable) via the JetBrains repository to handle the R# release cycle.

- [x] Use GitHub Actions (#103)
- [x] Run job once a every day (only if there are new commits) (#103)
- [x] Build and pack (#103)
- [x] Create a GitHub Release (#103)
- [x] Attach nupkg file to the release (#103)
- [x] Increment version in nuspec file\* (#103)
- [x] Increment version in assembly file\* (#112)
- [x] Push changes (#103)
- [x] Push nupkg file to the JetBrains repository (#106)
- [x] Use SemVer in nuspec file (#104) [deprecated]
- [x] GitHub Actions shouldn't fail if no changes were found (#111)

\* Currently recorded version is the current development version

**Comment by ManticSic** [comment]
Bug:  
nuspec file uses semantic version (major.minor.patch[-pre-release]) instead of major.minor.build.revision

**Comment by ManticSic** [comment]
@RicoSuter can you please add a secret for the automated upload or give me the requiered rights.
I will message you the key and the value.
Or can you give me the required rights to add one?
You can find the secret section at `Repository > Settings > Secrets`

**Comment by RicoSuter** [comment]
@ManticSic you're admin now.

**Comment by ManticSic** [comment]
Thanks @RicoSuter  
I will arrange everything this weekend
